package com.energie.platform.controller;
import com.energie.platform.dto.Dtos.*; import com.energie.platform.service.*; import io.swagger.v3.oas.annotations.*; import io.swagger.v3.oas.annotations.security.SecurityRequirement; import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/admin") @Tag(name="Administration") @SecurityRequirement(name="bearerAuth") @RequiredArgsConstructor public class AdminController {private final AuthService auth;private final FormulaireService formulaires;private final ProduitService produits;private final RegionService regions;private final RendezVousService rendezVous;private final AdminService admin;
 @PostMapping("/auth/login") @Operation(summary="Connexion administrateur") public TokenResponse login(@Valid @RequestBody LoginRequest r){return auth.login(r);}
 @GetMapping("/formulaires") @Operation(summary="Consulter les formulaires reçus") public List<FormulaireResponse> formulaires(){return formulaires.liste();}
 @GetMapping(value="/formulaires/export",produces="text/csv") @Operation(summary="Exporter le CRM au format CSV") public ResponseEntity<String> export(){return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=formulaires.csv").body(admin.exportCsv(formulaires.liste()));}
 @PostMapping("/produits") @ResponseStatus(HttpStatus.CREATED) @Operation(summary="Ajouter un produit") public ProduitResponse creerProduit(@Valid @RequestBody ProduitRequest r){return produits.creer(r);}
 @PutMapping("/produits/{id}") @Operation(summary="Modifier un produit") public ProduitResponse modifierProduit(@PathVariable Long id,@Valid @RequestBody ProduitRequest r){return produits.modifier(id,r);}
 @DeleteMapping("/produits/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Operation(summary="Supprimer un produit") public void supprimerProduit(@PathVariable Long id){produits.supprimer(id);}
 @PutMapping("/regions/{id}") @Operation(summary="Configurer lois, primes et champs d'une région") public RegionResponse modifierRegion(@PathVariable Long id,@Valid @RequestBody RegionUpdateRequest r){return regions.modifier(id,r);}
 @GetMapping("/rendez-vous") @Operation(summary="Consulter le planning") public List<RendezVousResponse> planning(){return rendezVous.liste();}
 @PutMapping("/rendez-vous/{id}") @Operation(summary="Modifier le statut d'un rendez-vous") public RendezVousResponse modifierRendezVous(@PathVariable Long id,@Valid @RequestBody RendezVousStatutRequest r){return rendezVous.modifier(id,r);}
 @GetMapping("/statistiques") @Operation(summary="Consulter le tableau de bord") public ResponseEntity<StatistiquesResponse> statistiques(){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(admin.statistiques());}}
