package com.energie.platform.controller;
import com.energie.platform.dto.Dtos.*; import com.energie.platform.service.*; import io.swagger.v3.oas.annotations.*; import io.swagger.v3.oas.annotations.security.SecurityRequirement; import io.swagger.v3.oas.annotations.tags.Tag; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/ai") @Tag(name="IA externe",description="Endpoints d'échange sécurisés avec X-API-KEY") @SecurityRequirement(name="aiApiKey") @RequiredArgsConstructor public class AiController {private final SimulationService simulations;private final ChatbotService chatbot;
 @GetMapping("/simulations/en-attente") @Operation(summary="Lister les simulations à calculer") public List<SimulationResponse> enAttente(){return simulations.enAttente();}
 @GetMapping("/simulations/{id}/contexte") @Operation(summary="Lire le contexte complet d'une simulation") public SimulationContexteResponse contexteSimulation(@PathVariable Long id){return simulations.contexte(id);}
 @PostMapping("/simulations/{id}/resultat") @Operation(summary="Enregistrer le résultat calculé par le service IA") public SimulationResponse resultat(@PathVariable Long id,@Valid @RequestBody SimulationResultatRequest r){return simulations.enregistrerResultat(id,r);}
 @GetMapping("/chatbot/messages/en-attente") @Operation(summary="Lister les messages visiteurs en attente") public List<MessageResponse> messages(){return chatbot.enAttente();}
 @GetMapping("/chatbot/conversations/{id}/contexte") @Operation(summary="Lire l'historique et le contexte chatbot") public ConversationContexteResponse contexteConversation(@PathVariable Long id){return chatbot.contexte(id);}
 @PostMapping("/chatbot/messages/{id}/reponse") @Operation(summary="Enregistrer une réponse IA") public MessageResponse reponse(@PathVariable Long id,@Valid @RequestBody ReponseIARequest r){return chatbot.enregistrerReponseIA(id,r);}
 @PostMapping("/chatbot/conversations/{id}/simulations") @Operation(summary="Créer une simulation depuis une conversation IA") public SimulationResponse simulation(@PathVariable Long id,@Valid @RequestBody AiSimulationRequest r){return chatbot.gererSimulation(id,r.formulaireId(),r.produitId());}
 @PostMapping("/chatbot/conversations/{id}/rendez-vous") @Operation(summary="Planifier un rendez-vous depuis une conversation") public RendezVousResponse rendezVous(@PathVariable Long id,@Valid @RequestBody AiRendezVousRequest r){return chatbot.gererPriseRDV(id,r.date(),r.heure());}
 @PutMapping("/chatbot/conversations/{id}/rendez-vous/{rendezVousId}") @Operation(summary="Modifier un rendez-vous depuis une conversation") public RendezVousResponse modifierRendezVous(@PathVariable Long id,@PathVariable Long rendezVousId,@Valid @RequestBody AiRendezVousRequest r){return chatbot.modifierRendezVous(id,rendezVousId,r.date(),r.heure());}
 @PutMapping("/chatbot/conversations/{id}/rendez-vous/{rendezVousId}/annuler") @Operation(summary="Annuler un rendez-vous depuis une conversation") public RendezVousResponse annulerRendezVous(@PathVariable Long id,@PathVariable Long rendezVousId){return chatbot.annulerRendezVous(id,rendezVousId);}}
