package com.energie.platform.service;
import com.energie.platform.dto.Dtos.*; import com.energie.platform.exception.ApiException; import com.energie.platform.model.*; import com.energie.platform.repository.Repositories.*; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*;
@Service @RequiredArgsConstructor public class ChatbotService {private final ChatbotIARepository conversations;private final MessageConversationRepository messages;private final VisiteurService visiteurs;private final ProduitService produits;private final FormulaireService formulaires;private final RendezVousService rendezVous;
 @Transactional public MessageResponse enregistrerMessageVisiteur(MessageCreationRequest r){ChatbotIA c=r.conversationId()==null?conversations.findByVisiteurId(r.visiteurId()).orElseGet(()->nouvelle(r.visiteurId())):conversation(r.conversationId());if(!c.getVisiteur().getId().equals(r.visiteurId()))throw new ApiException(HttpStatus.BAD_REQUEST,"Conversation et visiteur incohérents");MessageConversation m=new MessageConversation();m.setConversation(c);m.setContenu(r.message());m.setAuteur(AuteurMessage.VISITEUR);m.setStatut(StatutMessage.EN_ATTENTE);return Mapping.message(messages.save(m));}
 private ChatbotIA nouvelle(Long visiteurId){ChatbotIA c=new ChatbotIA();c.setVisiteur(visiteurs.get(visiteurId));c.setHistoriqueConversation("");return conversations.save(c);}
 @Transactional(readOnly=true) public ChatbotIA conversation(Long id){return conversations.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Conversation introuvable"));}
 @Transactional public MessageResponse enregistrerReponseIA(Long id,ReponseIARequest r){MessageConversation question=messages.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Message introuvable"));if(question.getAuteur()!=AuteurMessage.VISITEUR)throw new ApiException(HttpStatus.BAD_REQUEST,"Seul un message visiteur peut recevoir une réponse");if(question.getStatut()==StatutMessage.REPONDU)throw new ApiException(HttpStatus.CONFLICT,"Message déjà répondu");MessageConversation answer=new MessageConversation();answer.setConversation(question.getConversation());answer.setContenu(r.reponse());answer.setAuteur(AuteurMessage.IA);answer.setStatut(StatutMessage.REPONDU);messages.save(answer);question.setStatut(StatutMessage.REPONDU);messages.save(question);return Mapping.message(answer);}
 @Transactional(readOnly=true) public ConversationResponse consulterConversation(Long id){return Mapping.conversation(conversation(id));}
 @Transactional(readOnly=true) public List<MessageResponse> enAttente(){return messages.findByStatutAndAuteur(StatutMessage.EN_ATTENTE,AuteurMessage.VISITEUR).stream().map(Mapping::message).toList();}
 @Transactional(readOnly=true) public ConversationContexteResponse contexte(Long id){ChatbotIA c=conversation(id);return new ConversationContexteResponse(Mapping.conversation(c),produits.liste(null),formulaires.parVisiteur(c.getVisiteur().getId()));}
 @Transactional public RendezVousResponse gererPriseRDV(Long conversationId,LocalDate date,String heure){return rendezVous.creer(conversation(conversationId).getVisiteur().getId(),date,heure);}
}
