package com.energie.platform.service;
import com.energie.platform.dto.Dtos.*; import com.energie.platform.exception.ApiException; import com.energie.platform.model.*; import com.energie.platform.repository.Repositories.*; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class SimulationService {private final SimulationRepository repo;private final ScoreRepository scores;private final FormulaireService formulaires;private final ProduitService produits;
 @Transactional public SimulationResponse creerSimulation(SimulationCreationRequest r){Formulaire f=formulaires.get(r.formulaireId());Simulation s=new Simulation();s.setFormulaire(f);s.setVisiteur(f.getVisiteur());s.setProduit(produits.get(r.produitId()));s.setDateCalcul(LocalDateTime.now());s.setStatut(StatutSimulation.EN_ATTENTE);return Mapping.simulation(repo.save(s));}
 @Transactional(readOnly=true) public Simulation get(Long id){return repo.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Simulation introuvable"));}
 @Transactional(readOnly=true) public List<SimulationResponse> enAttente(){return repo.findByStatut(StatutSimulation.EN_ATTENTE).stream().map(Mapping::simulation).toList();}
 @Transactional public SimulationResponse enregistrerResultat(Long id,SimulationResultatRequest r){Simulation s=get(id);s.setCoutEstime(r.coutEstime());s.setStatut(StatutSimulation.TERMINEE);Score score=s.getScore();if(score==null){score=new Score();score.setSimulation(s);}score.setValeur(r.scoreValeur());score.setCriteres(r.scoreCriteres());score.getRecommandations().clear();for(String description:r.recommandations()){Recommandation rec=new Recommandation();rec.setDescription(description);rec.setScore(score);score.getRecommandations().add(rec);}scores.save(score);s.setScore(score);return Mapping.simulation(repo.save(s));}
 @Transactional(readOnly=true) public SimulationResponse consulterResultat(Long id){return Mapping.simulation(get(id));}
 @Transactional(readOnly=true) public SimulationContexteResponse contexte(Long id){Simulation s=get(id);return new SimulationContexteResponse(s.getId(),Mapping.formulaire(s.getFormulaire()),Mapping.produit(s.getProduit()),Mapping.visiteur(s.getVisiteur()),s.getFormulaire().getRegions().stream().map(Mapping::region).toList());}
}
