spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energie_plateforme
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
